In [33]:
import pandas as pd
import numpy as np

In [36]:
data = pd.read_csv("dnd-dataframe.csv")
data.head(14)

name  herotype  \
0                 bam      Bard   
1                niem  Sorcerer   
2                 aem   Paladin   
3               yaeks     Rogue   
4               jeeks     Druid   
5                 aez  Sorcerer   
6                 sax      Bard   
7                eert      Bard   
8                 wuc  Sorcerer   
9                 yac  Sorcerer   
10  Jocelyn Churchill   Paladin   
11       Robert Perry     Rogue   
12        Tim Carlton     Rogue   
13         Rolf Rylan   Paladin   

                                            weapons  \
0                               Dagger, sling, club   
1                         light crossbow, battleaxe   
2                                          Greataxe   
3                                   club, battleaxe   
4                                  Dagger, Greataxe   
5                              club, light crossbow   
6   light crossbow, battleaxe,  Dagger, sling, club   
7                                          Greataxe   
8                         light crossbow, battleaxe   
9                                          Greataxe   
10                                             club   
11                              Dagger, sling, club   
12                            light crossbow, sling   
13                        light crossbow, battleaxe   

                                   spells  
0             Transmutation, Enchantment   
1                             Necromancy   
2                 Abjuration, Conjuration  
3   Conjuration, Evocation, Transmutation  
4   Evocation, Transmutation, Necromancy   
5                 Evocation, Enchantment   
6                             Necromancy   
7              Transmutation, Necromancy   
8                             Necromancy   
9   Conjuration, Evocation, Transmutation  
10                Evocation, Enchantment   
11                Abjuration, Conjuration  
12                            Necromancy   
13                            Necromancy

In [43]:
dummies = data['weapons'].str.get_dummies(sep=',') 

In [44]:

dum_weapon = pd.concat([data, dummies], axis=1) 

In [45]:
dum_weapon.head()

name  herotype                    weapons  \
0    bam      Bard        Dagger, sling, club   
1   niem  Sorcerer  light crossbow, battleaxe   
2    aem   Paladin                   Greataxe   
3  yaeks     Rogue            club, battleaxe   
4  jeeks     Druid           Dagger, Greataxe   

                                  spells    Dagger   Greataxe   battleaxe  \
0            Transmutation, Enchantment          0          0           0   
1                            Necromancy          0          0           1   
2                Abjuration, Conjuration         0          0           0   
3  Conjuration, Evocation, Transmutation         0          0           1   
4  Evocation, Transmutation, Necromancy          0          1           0   

    club   light crossbow   sling  Dagger  Greataxe  club  light crossbow  
0      1                0       1       1         0     0               0  
1      0                0       0       0         0     0               1  
2      0                0       0       0         1     0               0  
3      0                0       0       0         0     1               0  
4      0                0       0       1         0     0               0

In [49]:
dummies1 = data['spells'].str.get_dummies(sep=',') 

In [50]:
dum_spells = pd.concat([data, dummies1], axis=1) 

In [53]:
dum_weapon.head()

name  herotype                    weapons  \
0    bam      Bard        Dagger, sling, club   
1   niem  Sorcerer  light crossbow, battleaxe   
2    aem   Paladin                   Greataxe   
3  yaeks     Rogue            club, battleaxe   
4  jeeks     Druid           Dagger, Greataxe   

                                  spells    Dagger   Greataxe   battleaxe  \
0            Transmutation, Enchantment          0          0           0   
1                            Necromancy          0          0           1   
2                Abjuration, Conjuration         0          0           0   
3  Conjuration, Evocation, Transmutation         0          0           1   
4  Evocation, Transmutation, Necromancy          0          1           0   

    club   light crossbow   sling  Dagger  Greataxe  club  light crossbow  
0      1                0       1       1         0     0               0  
1      0                0       0       0         0     0               1  
2      0                0       0       0         1     0               0  
3      0                0       0       0         0     1               0  
4      0                0       0       1         0     0               0

In [52]:
dum_spells.head()

name  herotype                    weapons  \
0    bam      Bard        Dagger, sling, club   
1   niem  Sorcerer  light crossbow, battleaxe   
2    aem   Paladin                   Greataxe   
3  yaeks     Rogue            club, battleaxe   
4  jeeks     Druid           Dagger, Greataxe   

                                  spells   Conjuration   Enchantment   \
0            Transmutation, Enchantment              0              1   
1                            Necromancy              0              0   
2                Abjuration, Conjuration             1              0   
3  Conjuration, Evocation, Transmutation             0              0   
4  Evocation, Transmutation, Necromancy              0              0   

    Evocation   Necromancy    Transmutation  Abjuration  Conjuration  \
0           0             0               0           0            0   
1           0             0               0           0            0   
2           0             0               0           1            0   
3           1             0               1           0            1   
4           0             1               1           0            0   

   Evocation  Necromancy   Transmutation  
0          0            0              1  
1          0            1              0  
2          0            0              0  
3          0            0              0  
4          1            0              0

spells  weapons_Dagger, Greataxe  \
0                Abjuration, Conjuration                         0   
1  Conjuration, Evocation, Transmutation                         0   
2                Evocation, Enchantment                          0   
3  Evocation, Transmutation, Necromancy                          1   
4                            Necromancy                          0   

   weapons_Dagger, sling, club  weapons_Greataxe  weapons_club  \
0                            1                 1             0   
1                            0                 1             0   
2                            0                 1             1   
3                            0                 0             0   
4                            0                 0             0   

   weapons_club, battleaxe  weapons_club, light crossbow  \
0                        0                             0   
1                        1                             0   
2                        0                             1   
3                        0                             0   
4                        0                             0   

   weapons_light crossbow, battleaxe  \
0                                  0   
1                                  0   
2                                  0   
3                                  0   
4                                  3   

   weapons_light crossbow, battleaxe,  Dagger, sling, club  \
0                                                  0         
1                                                  0         
2                                                  0         
3                                                  0         
4                                                  1         

   weapons_light crossbow, sling  
0                              0  
1                              0  
2                              0  
3                              0  
4                              1

In [61]:
stacked = dum_spells.stack()
index = stacked.index.get_level_values(0)
result = pd.crosstab(index=index, columns=stacked)
result.index.name = None
result.columns.name = None

In [62]:
result.head(13)

0  1  Abjuration, Conjuration  Bard  \
0   8  2                        0     1   
1   9  1                        0     0   
2   8  2                        1     0   
3   7  3                        0     0   
4   7  3                        0     0   
5   8  2                        0     0   
6   9  1                        0     1   
7   8  2                        0     1   
8   9  1                        0     0   
9   7  3                        0     0   
10  8  2                        0     0   
11  8  2                        1     0   
12  9  1                        0     0   

    Conjuration, Evocation, Transmutation  Dagger, Greataxe  \
0                                       0                 0   
1                                       0                 0   
2                                       0                 0   
3                                       1                 0   
4                                       0                 1   
5                                       0                 0   
6                                       0                 0   
7                                       0                 0   
8                                       0                 0   
9                                       1                 0   
10                                      0                 0   
11                                      0                 0   
12                                      0                 0   

    Dagger, sling, club  Druid  Evocation, Enchantment   \
0                     1      0                        0   
1                     0      0                        0   
2                     0      0                        0   
3                     0      0                        0   
4                     0      1                        0   
5                     0      0                        1   
6                     0      0                        0   
7                     0      0                        0   
8                     0      0                        0   
9                     0      0                        0   
10                    0      0                        1   
11                    1      0                        0   
12                    0      0                        0   

    Evocation, Transmutation, Necromancy   ...  eert  jeeks  \
0                                       0  ...     0      0   
1                                       0  ...     0      0   
2                                       0  ...     0      0   
3                                       0  ...     0      0   
4                                       1  ...     0      1   
5                                       0  ...     0      0   
6                                       0  ...     0      0   
7                                       0  ...     1      0   
8                                       0  ...     0      0   
9                                       0  ...     0      0   
10                                      0  ...     0      0   
11                                      0  ...     0      0   
12                                      0  ...     0      0   

    light crossbow, battleaxe  \
0                           0   
1                           1   
2                           0   
3                           0   
4                           0   
5                           0   
6                           0   
7                           0   
8                           1   
9                           0   
10                          0   
11                          0   
12                          0   

    light crossbow, battleaxe,  Dagger, sling, club  light crossbow, sling  \
0                                                 0                      0   
1                                                 0                      0   
2                                                 0                      0   
3                                

In [68]:
# use pd.concat to join the new columns with your original dataframe
dum_spells = pd.concat([data,pd.get_dummies(data['spells'], prefix='spells')],axis=1)

# now drop the original 'country' column (you don't need it anymore)
dum_spells.drop(['spells'],axis=1, inplace=True)

In [69]:
dum_spells.head(13)

name  herotype  \
0                 bam      Bard   
1                niem  Sorcerer   
2                 aem   Paladin   
3               yaeks     Rogue   
4               jeeks     Druid   
5                 aez  Sorcerer   
6                 sax      Bard   
7                eert      Bard   
8                 wuc  Sorcerer   
9                 yac  Sorcerer   
10  Jocelyn Churchill   Paladin   
11       Robert Perry     Rogue   
12        Tim Carlton     Rogue   

                                            weapons  \
0                               Dagger, sling, club   
1                         light crossbow, battleaxe   
2                                          Greataxe   
3                                   club, battleaxe   
4                                  Dagger, Greataxe   
5                              club, light crossbow   
6   light crossbow, battleaxe,  Dagger, sling, club   
7                                          Greataxe   
8                         light crossbow, battleaxe   
9                                          Greataxe   
10                                             club   
11                              Dagger, sling, club   
12                            light crossbow, sling   

    spells_Abjuration, Conjuration  \
0                                0   
1                                0   
2                                1   
3                                0   
4                                0   
5                                0   
6                                0   
7                                0   
8                                0   
9                                0   
10                               0   
11                               1   
12                               0   

    spells_Conjuration, Evocation, Transmutation  \
0                                              0   
1                                              0   
2                                              0   
3                                              1   
4                                              0   
5                                              0   
6                                              0   
7                                              0   
8                                              0   
9                                              1   
10                                             0   
11                                             0   
12                                             0   

    spells_Evocation, Enchantment   \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   
5                                1   
6                                0   
7                                0   
8                                0   
9                                0   
10                               1   
11                               0   
12                               0   

    spells_Evocation, Transmutation, Necromancy   spells_Necromancy   \
0                                              0                   0   
1                                              0                   1   
2                                              0                   0   
3                                              0                   0   
4                                              1                   0   
5                                              0                   0   
6                                              0                   1   
7                                              0                   0   
8                                              0                   1   
9                                              0                   0   
10                                             0                   0   
11                                             0                   0   
12                      

In [70]:
# use pd.concat to join the new columns with your original dataframe
dum_weapons = pd.concat([dum_spells,pd.get_dummies(dum_spells['weapons'], prefix='weapons')],axis=1)

# now drop the original 'country' column (you don't need it anymore)
dum_weapons.drop(['weapons'],axis=1, inplace=True)

In [71]:
dum_weapons.head(13)

name  herotype  spells_Abjuration, Conjuration  \
0                 bam      Bard                               0   
1                niem  Sorcerer                               0   
2                 aem   Paladin                               1   
3               yaeks     Rogue                               0   
4               jeeks     Druid                               0   
5                 aez  Sorcerer                               0   
6                 sax      Bard                               0   
7                eert      Bard                               0   
8                 wuc  Sorcerer                               0   
9                 yac  Sorcerer                               0   
10  Jocelyn Churchill   Paladin                               0   
11       Robert Perry     Rogue                               1   
12        Tim Carlton     Rogue                               0   

    spells_Conjuration, Evocation, Transmutation  \
0                                              0   
1                                              0   
2                                              0   
3                                              1   
4                                              0   
5                                              0   
6                                              0   
7                                              0   
8                                              0   
9                                              1   
10                                             0   
11                                             0   
12                                             0   

    spells_Evocation, Enchantment   \
0                                0   
1                                0   
2                                0   
3                                0   
4                                0   
5                                1   
6                                0   
7                                0   
8                                0   
9                                0   
10                               1   
11                               0   
12                               0   

    spells_Evocation, Transmutation, Necromancy   spells_Necromancy   \
0                                              0                   0   
1                                              0                   1   
2                                              0                   0   
3                                              0                   0   
4                                              1                   0   
5                                              0                   0   
6                                              0                   1   
7                                              0                   0   
8                                              0                   1   
9                                              0                   0   
10                                             0                   0   
11                                             0                   0   
12                                             0                   1   

    spells_Transmutation, Enchantment   spells_Transmutation, Necromancy   \
0                                    1                                  0   
1                                    0                                  0   
2                                    0                                  0   
3                                    0                                  0   
4                                    0                                  0   
5                                    0                                  0   
6                                    0                                  0   
7                                    0                                  1   
8                                    0                                  0   
9                                    

In [76]:
y = pd.get_dummies(data.spells, prefix='spells')
print(y.head())

   spells_Abjuration, Conjuration  \
0                               0   
1                               0   
2                               1   
3                               0   
4                               0   

   spells_Conjuration, Evocation, Transmutation  \
0                                             0   
1                                             0   
2                                             0   
3                                             1   
4                                             0   

   spells_Evocation, Enchantment   \
0                               0   
1                               0   
2                               0   
3                               0   
4                               0   

   spells_Evocation, Transmutation, Necromancy   spells_Necromancy   \
0                                             0                   0   
1                                             0                   1   
2                                 

In [73]:
from sklearn.preprocessing import LabelBinarizer

In [77]:
y = LabelBinarizer().fit_transform(data.spells)

In [78]:
from sklearn.preprocessing import OneHotEncoder

In [79]:
x = [[2, "yaeks"], [0, "bam"], [10, "Jocelyn Churchill"], [6, "sax"], [4, "jeeks"]]
y = OneHotEncoder().fit_transform(x).toarray()
print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]]


TypeError: 'numpy.ndarray' object is not callable